### ISSUE TITLE
全局message 控制台提示[antd: message] Static function can not consume

### ISSUE THREAD

**Issue by Hyebin98** [southliu/react-admin#107]
暂时的解决方法：https://github.com/ant-design/ant-design/discussions/41855

**Comment by southliu** [comment]
使用useApp()解决： https://ant.design/components/app-cn#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

**Comment by Hyebin98** [comment]
> 使用useApp()解决： https://ant.design/components/app-cn#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

axios拦截器中使用了antd的message组件 如果在登录页面密码错误 控制台就会有这个警告
![image](https://github.com/southliu/react-admin/assets/49463883/e930fbf2-7ad9-464a-8984-dc354429adce)

**Comment by Hyebin98** [comment]
暂时的解决方案 你可以看一下 
https://github.com/ant-design/ant-design/discussions/41855#discussioncomment-5706550

**Comment by southliu** [comment]
好的，我研究一下

**Comment by southliu** [comment]
感谢！已解决
