### ISSUE TITLE
请问使用的哪个版本的node，pnpm，打包编译后没有问题，但是线上部署出错

### ISSUE THREAD

**Issue by qindan-00** [southliu/react-admin#118]
Uncaught TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
    at react-dom.faae5cda.js:9:5345 #

**Comment by southliu** [comment]
我本地16.14.2没问题，推荐使用16+版本。https://cn.vitejs.dev/guide/

**Comment by scjianlin** [comment]
这好事是vite的bug. 我也遇到了。https://github.com/alibaba/x-render/issues/1207

**Comment by qindan-00** [comment]
感谢感谢，去掉静态资源分类打包配置，现在好了
