### ISSUE TITLE
如何添加菜单项

### ISSUE THREAD

**Issue by raoqu** [southliu/react-admin#130]
我在pages/demo下增加了目录spreadsheet，通过url可以正常访问
在menus/demo.ts中增加或不增加以下配置代码都没有看到菜单项

      {
        label: '表格',
        labelEn: 'Spreadsheet',
        key: '/demo/spreadsheet',
        rule: '/demo/spreadsheet',
      },
请问菜单的详细规则

**Comment by southliu** [comment]
如果是静态菜单，就需要改以下内容，目前菜单是从接口获取的。
![image](https://github.com/southliu/react-admin/assets/26358837/93a4ef03-b218-4a79-bfb4-3c4fb7c0c64f)

**Comment by raoqu** [comment]
看起来对我似乎并没有生效
<img width="595" alt="image" src="https://github.com/southliu/react-admin/assets/1956572/e5de015b-37f5-49c4-a071-1f754655d988">
新增的页面目录结构
+ pages
 + dashboard
 + terminal
  + index.tsx
useCommonStore.ts代码为：
  // 动态菜单
  // const menuList = useSelector((state: RootState) => state.menu.menuList);
  // 静态菜单
  const menuList = defaultMenus;

期望是用动态菜单 ，是因为动态菜单对我也同样没有生效才考虑改成静态菜单

**Comment by southliu** [comment]
{
    label: '表格',
    labelEn: 'Spreadsheet',
    key: '/demo/spreadsheet',
    rule: '/demo/copy', // 这里的菜单权限改成现有的权限
  },

权限也需要从接口获取

**Comment by raoqu** [comment]
Thanks，是我没有注意到是从server端获取的
