### ISSUE TITLE
项目下载后安装好依赖，运行后错误提示，请问这个如何解决呢

### ISSUE THREAD

**Issue by Howie7793** [southliu/react-admin#171]
运行错误提示：findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:

顺便请教下作者，我想要接入页面权限，有详细操作步骤嘛。谢谢

**Comment by southliu** [comment]
这个错误会影响页面显示吗？

页面权限：
1. 通过登录接(/login/v2)或重新授权接口(/authority/user/refresh-permissions/v2)获取permissions权限数据。
2. 通过菜单接口(/menu/list/v3)获取data中的rule权限数据，这个rule数据影响菜单显示，如果没返回rule则一直都显示。
3. 页面内权限参考src/pages/system/menu.index.tsx文件内的pagePermission数据，pagePermission.page是显示页面的权限，根据第一点返回的permissions进行匹配。

**Comment by southliu** [comment]
这个错误提示可参考：https://github.com/ant-design/ant-design/issues/48709#issuecomment-2196130505
目前打算等antd升级解决该问题。

**Comment by Howie7793** [comment]
谢谢反馈，那就是 /menu/list/v3 接口是我该平台上的所有页面菜单数据，  /authority/user/refresh-permissions/v2 接口是该用户的页面权限数据。   然后模板会自动根据v3中过滤出v2中有的数据，然后使用作为页面展示。   是我理解的这个意思嘛， 这样我只需要修改这两个接口即可。

**Comment by Howie7793** [comment]
页面权限可以了，谢谢解答，希望作者大大后面可以优化掉findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:这个错误。 前面按你给的ant-design的问题中没解决

**Comment by Tangfan429** [comment]
Stylelint 报错: Unknown rule
