### ISSUE TITLE
代理服务访问不了

### ISSUE THREAD

**Issue by chy9610** [southliu/react-admin#191]
项目的代理服务关了吗？

**Comment by Tangfan429** [comment]
开发环境的代理服务不是正常的吗?

**Comment by chy9610** [comment]
![image](https://github.com/user-attachments/assets/f642195d-5e2a-42b2-ab95-4e7a1a5aff4a)
我这边代理访问服务器异常

**Comment by chy9610** [comment]
我启动项目代理服务显示500 -。-

**Comment by southliu** [comment]
有图片能让我看看你是怎么配置的吗？.env.xxx文件有跟着改吗？

**Comment by southliu** [comment]
如果是发布至生产，就需要配置nginx进行反向代理。

**Comment by chy9610** [comment]
我拷贝之后本地启动dev，没改动配置(●'◡'●)

**Comment by southliu** [comment]
有图片看看具体报什么错误吗

**Comment by chy9610** [comment]
![微信图片_20240930113809](https://github.com/user-attachments/assets/d77bc969-a85c-43ea-bda5-d37f1e248aa4)

**Comment by southliu** [comment]
是pnpm dev启动吗？.env.development的配置是这个吗：
```
# 跨域
VITE_PROXY = [["/api", "https://mock.mengxuegu.com/mock/63f830b1c5a76a117cab185e/v1"]]
```

**Comment by chy9610** [comment]
是的

**Comment by chy9610** [comment]
我本地网络问题导致的，抱歉😂

**Comment by betterZCH** [comment]
> 我本地网络问题导致的，抱歉😂

最后怎么解决的？我也出了一样的错误，但是我可以正常上网啊

**Comment by southliu** [comment]
> > 我本地网络问题导致的，抱歉😂
> 
> 最后怎么解决的？我也出了一样的错误，但是我可以正常上网啊
你用了梯子吗？尝试关掉梯子试试？

**Comment by betterZCH** [comment]
> > > 我本地网络问题导致的，抱歉😂
> > 
> > 
> > 最后怎么解决的？我也出了一样的错误，但是我可以正常上网啊
> 
> 你用了梯子吗？尝试关掉梯子试试？

我把我的网络都重置了，也还是不行。明明中午还能用，吃了饭回来就不行了

**Comment by southliu** [comment]
> > > > 我本地网络问题导致的，抱歉😂
> > > 
> > > 
> > > 最后怎么解决的？我也出了一样的错误，但是我可以正常上网啊
> > 
> > 
> > 你用了梯子吗？尝试关掉梯子试试？
> 
> 我把我的网络都重置了，也还是不行。明明中午还能用，吃了饭回来就不行了

不是你的问题，mock平台崩了，我得晚上回去看看什么情况😨

**Comment by betterZCH** [comment]
> > > > > 我本地网络问题导致的，抱歉😂
> > > > 
> > > > 
> > > > 最后怎么解决的？我也出了一样的错误，但是我可以正常上网啊
> > > 
> > > 
> > > 你用了梯子吗？尝试关掉梯子试试？
> > 
> > 
> > 我把我的网络都重置了，也还是不行。明明中午还能用，吃了饭回来就不行了
> 
> 不是你的问题，mock平台崩了，我得晚上回去看看什么情况😨

太感谢了，这么及时回复，我还在焦头烂额的找代码哪里错了

**Comment by southliu** [comment]
> 太感谢了，这么及时回复，我还在焦头烂额的找代码哪里错了

mock平台恢复了，可以正常使用了，周末我再加个其他平台mock链接上去，预防这种情况发生。
