### ISSUE TITLE
使用新的 keep-alive 缓存组件

### ISSUE THREAD

**Issue by condorheroblog** [southliu/react-admin#201]
react-activation 确实是一个优秀的项目，早期我的项目都是使用这个开源仓库，但是这个项目有一个非常严重的问题，在和 antd 的 Modal 等组件一起使用，路由切换被缓存的组件会重新触发某些动画效果，比如 Modal 组件会打开一下然后关闭，按钮如果有 loading 也会自动触发然后关闭，对代码倒是不影响，但是体验不好。相关问题链接：[react-activation](https://github.com/CJY0208/react-activation/issues/225#issuecomment-1311136388)

建议使用 https://github.com/irychen/keepalive-for-react 进行替换，一个新的但是也是非常优秀的项目。

**Comment by condorheroblog** [comment]
请允许我补充一个说明，方便你更好的理解，如下就是上面提到那个问题的演示，明显看到 Modal 打开关闭，和 Select 组件选项卡的打开和关闭。

![Kapture 2024-10-11 at 11 27 54](https://github.com/user-attachments/assets/d8780e7f-ef21-43dd-8e35-d9101ccb2de1)

**Comment by southliu** [comment]
好的大佬，我研究一下

**Comment by condorheroblog** [comment]
酷毙了👍

**Comment by EmmaCheny** [comment]
大脑怎么用的

**Comment by southliu** [comment]
> 大脑怎么用的

我不知道你具体要实现什么功能，你可以参考https://github.com/irychen/keepalive-for-react里面的文档，或者在这个开源项目搜索keepalive-for-react的使用方法。
