### ISSUE TITLE
开发环境编辑器代码保存之后，浏览器就提示403..

### ISSUE THREAD

**Issue by scjianlin** [southliu/react-admin#57]
![image](https://user-images.githubusercontent.com/25558117/218354335-d8cba8fc-5749-41a8-a138-2a96d8fc767b.png)

**Comment by scjianlin** [comment]
系统是mac m1, 浏览器Chrome, 按照README文档搞的环境。

**Comment by southliu** [comment]
麻烦尝试一下在 /build/plugins/index.ts里面把cachePlugin() 方法注释了在重新打开试试

**Comment by southliu** [comment]
要不加我微信研究一下具体是什么问题，lnf1275093225

**Comment by southliu** [comment]
要不加我微信研究一下具体是什么问题，lnf1275093225
