### ISSUE TITLE
关于带参数的多页签问题

### ISSUE THREAD

**Issue by f1704962** [southliu/react-admin#62]
之前我是加了2个按钮
![image](https://user-images.githubusercontent.com/40535742/224240953-5217ba9d-b615-4783-86e3-c8c4071b3267.png)
想要测一下带参数详情多页签问题，发现无效
![image](https://user-images.githubusercontent.com/40535742/224240998-3ab80fcc-a5f9-4058-9646-2597cbc2fd37.png)
后来我发现在编辑文章的时候，带参数的多页签的正常的，仔细看了一下，发现是在文章编辑这个页面，额外写了一段代码，因此，带参数的多页签只生效于文章编辑这个页面，因此我自己随便搞了2个按钮是无效的……我还以为我搞错了
![image](https://user-images.githubusercontent.com/40535742/224241191-0bf82029-6223-4931-8521-731574ae1096.png)

**Comment by southliu** [comment]
可以提供一下这两个按钮的代码片段吗？

**Comment by southliu** [comment]
![image](https://user-images.githubusercontent.com/26358837/224323732-e58b2b29-f90a-4473-a9ee-8bcb7d00a4a7.png)
我尝试模拟你的案例，没发现什么问题😅

**Comment by f1704962** [comment]
是我搞错了，老哥你这样写就比较合理，我是直接路由跳转了，没有加上临时页签添加的这块逻辑
