### ISSUE TITLE
导入路由模块用法求解

### ISSUE THREAD

**Issue by xiumubai** [southliu/react-admin#89]
`import routes from '~react-pages'`

老哥，这个是怎么导入路由页面的，这个写法第一次见

**Comment by southliu** [comment]
这是vite-plugin-pages插件提供的，具体看 https://www.npmjs.com/package/vite-plugin-pages 这里面有说。

**Comment by xiumubai** [comment]
好的，谢谢老哥，你的这个模版已经用在项目中了

**Comment by southliu** [comment]
嗯嗯，欢迎提bug。
